import { useState } from 'react';
import { AdvancedVideo, lazyload } from '@cloudinary/react';
import { buildReturnVideo, buildVideoThumbnailUrl } from '../cloudinaryConfig.ts';
import type { VideoTransform } from '../types/index.ts';

// Cloudinary demo account video public_id
// In production this is the merchant's uploaded how-to-return guide video
const DEMO_VIDEO_PUBLIC_ID = 'docs/cld-sample-video';

const VIDEO_TRANSFORMS: VideoTransform[] = [
  { icon: '🎥', name: 'Adaptive Quality', code: 'q_auto', desc: 'Auto quality per network speed' },
  { icon: '📐', name: 'Auto Format', code: 'f_auto', desc: 'Serves mp4/webm/av1 per browser' },
  { icon: '🖼️', name: 'Smart Poster', code: 'so_2,f_auto', desc: 'Auto thumbnail at 2 sec mark' },
  { icon: '✂️', name: 'Loop-ready', code: 'so_0,eo_15', desc: '15-sec guide clip' },
];

/**
 * Side Quest 2: Most innovative use of Cloudinary for video
 *
 * Uses AdvancedVideo from @cloudinary/react with @cloudinary/url-gen SDK.
 * Cloudinary delivers the merchant's how-to-return guide video with:
 * - Adaptive bitrate (q_auto) based on network conditions
 * - Auto format (f_auto) — mp4, webm, or av1 depending on browser support
 * - Auto-generated poster thumbnail from frame at 2 seconds (so_2)
 * - Global CDN delivery
 */
export default function VideoDemo() {
  const [playing, setPlaying] = useState<boolean>(false);

  const cldVideo = buildReturnVideo(DEMO_VIDEO_PUBLIC_ID);
  const thumbUrl = buildVideoThumbnailUrl(DEMO_VIDEO_PUBLIC_ID, 2);

  return (
    <div style={{ background: '#fff', borderRadius: 16, padding: 24, boxShadow: '0 2px 12px rgba(0,0,0,0.08)' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
        <div style={{ fontSize: 18, fontWeight: 700, color: '#1d1d1f' }}>How-to Return Video</div>
        <div style={{ fontSize: 12, fontWeight: 600, background: '#fff0e6', color: '#c05621', padding: '4px 10px', borderRadius: 20 }}>
          Side Quest 2: Video
        </div>
      </div>

      {/* Video player — AdvancedVideo from @cloudinary/react */}
      <div style={{ position: 'relative', borderRadius: 12, overflow: 'hidden', background: '#0a0a0a', aspectRatio: '16/9' }}>
        {playing ? (
          <AdvancedVideo
            cldVid={cldVideo}
            plugins={[lazyload()]}
            controls
            autoPlay
            poster={thumbUrl}
            style={{ width: '100%', height: '100%', objectFit: 'cover' }}
          />
        ) : (
          <>
            <img
              src={thumbUrl}
              alt="Video poster — auto-generated by Cloudinary at 2s mark"
              style={{ width: '100%', height: '100%', objectFit: 'cover' }}
            />
            <div style={{
              position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column',
              alignItems: 'center', justifyContent: 'center', gap: 16,
            }}>
              <button
                onClick={() => setPlaying(true)}
                style={{
                  width: 72, height: 72, borderRadius: '50%', background: 'rgba(255,255,255,0.9)',
                  border: 'none', cursor: 'pointer', fontSize: 28,
                  boxShadow: '0 4px 20px rgba(0,0,0,0.4)', transition: 'transform 0.2s',
                }}
              >
                ▶
              </button>
              <div style={{ color: 'rgba(255,255,255,0.85)', fontSize: 14, fontWeight: 500 }}>
                Cloudinary-served demo video
              </div>
            </div>
          </>
        )}
      </div>

      {/* Transform info cards */}
      <div style={{ marginTop: 16, padding: 16, background: '#f8f8fc', borderRadius: 12 }}>
        <div style={{ fontSize: 13, fontWeight: 700, color: '#374151', marginBottom: 12 }}>
          Applied Cloudinary Video Transforms
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
          {VIDEO_TRANSFORMS.map((t) => (
            <div key={t.code} style={{
              display: 'flex', alignItems: 'flex-start', gap: 8, padding: '8px 10px',
              background: '#fff', borderRadius: 8, border: '1px solid #e5e7eb',
            }}>
              <div style={{ fontSize: 16, flexShrink: 0, marginTop: 1 }}>{t.icon}</div>
              <div>
                <div style={{ fontSize: 12, color: '#374151' }}>{t.name}</div>
                <code style={{ fontSize: 11, color: '#6b7280' }}>{t.code}</code>
                <div style={{ fontSize: 11, color: '#9ca3af', marginTop: 2 }}>{t.desc}</div>
              </div>
            </div>
          ))}
        </div>
      </div>

      <p style={{ marginTop: 12, fontSize: 12, color: '#9ca3af', fontStyle: 'italic' }}>
        Rendered with <code>{'<AdvancedVideo>'}</code> from <code>@cloudinary/react</code>.
        Merchants upload their guide video via the Upload Widget tab and Cloudinary handles encoding + CDN delivery.
      </p>
    </div>
  );
}
